# Generated by Django 5.1.4 on 2025-01-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomno', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('adharno', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
