# Generated by Django 5.1.4 on 2025-01-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='personaldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
    ]
