# Generated by Django 5.1.4 on 2025-01-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_site', '0002_personaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_no', models.CharField(max_length=20)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('units_consumed', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
