# Generated by Django 5.1.4 on 2025-01-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_site', '0004_submeter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('totaltanker', models.IntegerField()),
                ('amounttanker', models.IntegerField()),
                ('maintenance', models.IntegerField()),
                ('tenantno', models.IntegerField()),
            ],
        ),
    ]
